export const industryOptions = [
  { value: "technology", label: "Technology" },
  { value: "finance", label: "Finance & Banking" },
  { value: "education", label: "Education & Training" },
  { value: "healthcare", label: "Healthcare & Medical" },
  { value: "marketing", label: "Marketing & Advertising" },
  { value: "real_estate", label: "Real Estate & Property" },
  { value: "media", label: "Media & Entertainment" },
  { value: "legal", label: "Legal & Law" },
  { value: "ecommerce", label: "E-commerce" },
  { value: "consulting", label: "Consulting & Strategy" },
  { value: "manufacturing", label: "Manufacturing & Production" },
  { value: "hospitality", label: "Hospitality & Tourism" },
  { value: "non_profit", label: "Non-profit & NGOs" },
  { value: "transportation", label: "Transportation & Logistics" },
  { value: "construction", label: "Construction & Engineering" },
  { value: "energy", label: "Energy & Utilities" },
  { value: "agriculture", label: "Agriculture & Farming" },
  { value: "fashion", label: "Fashion & Apparel" },
  { value: "gaming", label: "Gaming & Interactive Media" },
  { value: "cybersecurity", label: "Cybersecurity" },
  { value: "telecommunications", label: "Telecommunications" },
  { value: "sports", label: "Sports & Fitness" },
  { value: "food_beverage", label: "Food & Beverage" },
  { value: "automotive", label: "Automotive" },
  { value: "aerospace", label: "Aerospace & Aviation" },
];

export const industryEnum = [
  "technology",
  "finance",
  "education",
  "healthcare",
  "marketing",
  "real_estate",
  "media",
  "legal",
  "ecommerce",
  "consulting",
  "manufacturing",
  "hospitality",
  "non_profit",
  "transportation",
  "construction",
  "energy",
  "agriculture",
  "fashion",
  "gaming",
  "cybersecurity",
  "telecommunications",
  "sports",
  "food_beverage",
  "automotive",
  "aerospace",
] as const;

export type Industry = (typeof industryEnum)[number];
