// Global Keywords Database - Beyond Nigeria to All African Countries & International Markets

export const africanCountries = {
  // West Africa
  westAfrica: [
    "Ghana learning platform",
    "Ghana online courses",
    "Ghana freelancing",
    "Ghana jobs",
    "Ghana tech courses",
    "Ghana business courses",
    "Ghana writers",
    "Ghana bloggers",
    "Ghana social platform",
    "Ghana Udemy alternative",
    "Ghana Coursera alternative",
    "Ghana LinkedIn alternative",
    "Ghana best course platform",
    "Ghana freelance marketplace",
    "Ghana job opportunities",
    "Ghana AI courses",
    "Ghana programming courses",
    "Ghana digital marketing",
    "Ghana business network",
    "Ghana professional network",
    "Ghana course selling platform",
    "Ghana learning management system",
    "Ghana educational technology",
    "Ghana e-learning platform",
    "Ghana skill development",
    "Ghana professional training",
    "Ghana online learning",
    "Ghana course marketplace",
    "Ghana training platform",
    "Ghana educational platform",
  ],

  // East Africa
  eastAfrica: [
    "Kenya learning platform",
    "Kenya online courses",
    "Kenya freelancing",
    "Kenya jobs",
    "Kenya tech courses",
    "Kenya business courses",
    "Kenya writers",
    "Kenya bloggers",
    "Kenya social platform",
    "Kenya Udemy alternative",
    "Kenya Coursera alternative",
    "Kenya LinkedIn alternative",
    "Kenya best course platform",
    "Kenya freelance marketplace",
    "Kenya job opportunities",
    "Kenya AI courses",
    "Kenya programming courses",
    "Kenya digital marketing",
    "Kenya business network",
    "Kenya professional network",
    "Kenya course selling platform",
    "Kenya learning management system",
    "Kenya educational technology",
    "Kenya e-learning platform",
    "Kenya skill development",
    "Kenya professional training",
    "Kenya online learning",
    "Kenya course marketplace",
    "Kenya training platform",
    "Kenya educational platform",
    "Tanzania learning platform",
    "Tanzania online courses",
    "Tanzania freelancing",
    "Tanzania jobs",
    "Tanzania tech courses",
    "Tanzania business courses",
    "Tanzania writers",
    "Tanzania bloggers",
    "Tanzania social platform",
    "Uganda learning platform",
    "Uganda online courses",
    "Uganda freelancing",
    "Uganda jobs",
    "Uganda tech courses",
    "Uganda business courses",
    "Uganda writers",
    "Uganda bloggers",
    "Uganda social platform",
    "Rwanda learning platform",
    "Rwanda online courses",
    "Rwanda freelancing",
    "Rwanda jobs",
    "Rwanda tech courses",
    "Rwanda business courses",
    "Ethiopia learning platform",
    "Ethiopia online courses",
    "Ethiopia freelancing",
    "Ethiopia jobs",
    "Ethiopia tech courses",
    "Ethiopia business courses",
    "Ethiopia writers",
    "Ethiopia bloggers",
    "Ethiopia social platform",
  ],

  // Southern Africa
  southernAfrica: [
    "South Africa learning platform",
    "South Africa online courses",
    "South Africa freelancing",
    "South Africa jobs",
    "South Africa tech courses",
    "South Africa business courses",
    "South Africa writers",
    "South Africa bloggers",
    "South Africa social platform",
    "South Africa Udemy alternative",
    "South Africa Coursera alternative",
    "South Africa LinkedIn alternative",
    "South Africa best course platform",
    "South Africa freelance marketplace",
    "South Africa job opportunities",
    "South Africa AI courses",
    "South Africa programming courses",
    "South Africa digital marketing",
    "South Africa business network",
    "South Africa professional network",
    "South Africa course selling platform",
    "South Africa learning management system",
    "South Africa educational technology",
    "South Africa e-learning platform",
    "South Africa skill development",
    "South Africa professional training",
    "South Africa online learning",
    "South Africa course marketplace",
    "South Africa training platform",
    "South Africa educational platform",
    "Zimbabwe learning platform",
    "Zimbabwe online courses",
    "Zimbabwe freelancing",
    "Zimbabwe jobs",
    "Zimbabwe tech courses",
    "Zimbabwe business courses",
    "Zimbabwe writers",
    "Zimbabwe bloggers",
    "Zimbabwe social platform",
    "Botswana learning platform",
    "Botswana online courses",
    "Botswana freelancing",
    "Botswana jobs",
    "Botswana tech courses",
    "Botswana business courses",
    "Botswana writers",
    "Botswana bloggers",
    "Botswana social platform",
    "Namibia learning platform",
    "Namibia online courses",
    "Namibia freelancing",
    "Namibia jobs",
    "Namibia tech courses",
    "Namibia business courses",
    "Namibia writers",
    "Namibia bloggers",
    "Namibia social platform",
  ],

  // Central Africa
  centralAfrica: [
    "Cameroon learning platform",
    "Cameroon online courses",
    "Cameroon freelancing",
    "Cameroon jobs",
    "Cameroon tech courses",
    "Cameroon business courses",
    "Cameroon writers",
    "Cameroon bloggers",
    "Cameroon social platform",
    "Cameroon Udemy alternative",
    "Cameroon Coursera alternative",
    "Cameroon LinkedIn alternative",
    "Cameroon best course platform",
    "Cameroon freelance marketplace",
    "Cameroon job opportunities",
    "Cameroon AI courses",
    "Cameroon programming courses",
    "Cameroon digital marketing",
    "Cameroon business network",
    "Cameroon professional network",
    "Cameroon course selling platform",
    "Cameroon learning management system",
    "Cameroon educational technology",
    "Cameroon e-learning platform",
    "Cameroon skill development",
    "Cameroon professional training",
    "Cameroon online learning",
    "Cameroon course marketplace",
    "Cameroon training platform",
    "Cameroon educational platform",
    "Congo learning platform",
    "Congo online courses",
    "Congo freelancing",
    "Congo jobs",
    "Congo tech courses",
    "Congo business courses",
    "Congo writers",
    "Congo bloggers",
    "Congo social platform",
    "Gabon learning platform",
    "Gabon online courses",
    "Gabon freelancing",
    "Gabon jobs",
    "Gabon tech courses",
    "Gabon business courses",
    "Gabon writers",
    "Gabon bloggers",
    "Gabon social platform",
    "Chad learning platform",
    "Chad online courses",
    "Chad freelancing",
    "Chad jobs",
    "Chad tech courses",
    "Chad business courses",
    "Chad writers",
    "Chad bloggers",
    "Chad social platform",
  ],

  // North Africa
  northAfrica: [
    "Egypt learning platform",
    "Egypt online courses",
    "Egypt freelancing",
    "Egypt jobs",
    "Egypt tech courses",
    "Egypt business courses",
    "Egypt writers",
    "Egypt bloggers",
    "Egypt social platform",
    "Egypt Udemy alternative",
    "Egypt Coursera alternative",
    "Egypt LinkedIn alternative",
    "Egypt best course platform",
    "Egypt freelance marketplace",
    "Egypt job opportunities",
    "Egypt AI courses",
    "Egypt programming courses",
    "Egypt digital marketing",
    "Egypt business network",
    "Egypt professional network",
    "Egypt course selling platform",
    "Egypt learning management system",
    "Egypt educational technology",
    "Egypt e-learning platform",
    "Egypt skill development",
    "Egypt professional training",
    "Egypt online learning",
    "Egypt course marketplace",
    "Egypt training platform",
    "Egypt educational platform",
    "Morocco learning platform",
    "Morocco online courses",
    "Morocco freelancing",
    "Morocco jobs",
    "Morocco tech courses",
    "Morocco business courses",
    "Morocco writers",
    "Morocco bloggers",
    "Morocco social platform",
    "Tunisia learning platform",
    "Tunisia online courses",
    "Tunisia freelancing",
    "Tunisia jobs",
    "Tunisia tech courses",
    "Tunisia business courses",
    "Tunisia writers",
    "Tunisia bloggers",
    "Tunisia social platform",
    "Algeria learning platform",
    "Algeria online courses",
    "Algeria freelancing",
    "Algeria jobs",
    "Algeria tech courses",
    "Algeria business courses",
    "Algeria writers",
    "Algeria bloggers",
    "Algeria social platform",
    "Libya learning platform",
    "Libya online courses",
    "Libya freelancing",
    "Libya jobs",
    "Libya tech courses",
    "Libya business courses",
    "Libya writers",
    "Libya bloggers",
    "Libya social platform",
  ],
};

export const internationalKeywords = {
  // Diaspora Keywords
  diaspora: [
    "African diaspora learning platform",
    "African diaspora online courses",
    "African diaspora freelancing",
    "African diaspora jobs",
    "African diaspora tech courses",
    "African diaspora business courses",
    "African diaspora writers",
    "African diaspora bloggers",
    "African diaspora social platform",
    "African diaspora Udemy alternative",
    "African diaspora Coursera alternative",
    "African diaspora LinkedIn alternative",
    "African diaspora best course platform",
    "African diaspora freelance marketplace",
    "African diaspora job opportunities",
    "African diaspora AI courses",
    "African diaspora programming courses",
    "African diaspora digital marketing",
    "African diaspora business network",
    "African diaspora professional network",
    "African diaspora course selling platform",
    "African diaspora learning management system",
    "African diaspora educational technology",
    "African diaspora e-learning platform",
    "African diaspora skill development",
    "African diaspora professional training",
    "African diaspora online learning",
    "African diaspora course marketplace",
    "African diaspora training platform",
    "African diaspora educational platform",
    "Nigerian diaspora learning platform",
    "Nigerian diaspora online courses",
    "Nigerian diaspora freelancing",
    "Nigerian diaspora jobs",
    "Nigerian diaspora tech courses",
    "Nigerian diaspora business courses",
    "Nigerian diaspora writers",
    "Nigerian diaspora bloggers",
    "Nigerian diaspora social platform",
    "Ghanaian diaspora learning platform",
    "Ghanaian diaspora online courses",
    "Ghanaian diaspora freelancing",
    "Ghanaian diaspora jobs",
    "Ghanaian diaspora tech courses",
    "Ghanaian diaspora business courses",
    "Ghanaian diaspora writers",
    "Ghanaian diaspora bloggers",
    "Ghanaian diaspora social platform",
    "Kenyan diaspora learning platform",
    "Kenyan diaspora online courses",
    "Kenyan diaspora freelancing",
    "Kenyan diaspora jobs",
    "Kenyan diaspora tech courses",
    "Kenyan diaspora business courses",
    "Kenyan diaspora writers",
    "Kenyan diaspora bloggers",
    "Kenyan diaspora social platform",
    "South African diaspora learning platform",
    "South African diaspora online courses",
    "South African diaspora freelancing",
    "South African diaspora jobs",
    "South African diaspora tech courses",
    "South African diaspora business courses",
    "South African diaspora writers",
    "South African diaspora bloggers",
    "South African diaspora social platform",
  ],

  // International Markets
  international: [
    "Africa learning platform",
    "Africa online courses",
    "Africa freelancing",
    "Africa jobs",
    "Africa tech courses",
    "Africa business courses",
    "Africa writers",
    "Africa bloggers",
    "Africa social platform",
    "Africa Udemy alternative",
    "Africa Coursera alternative",
    "Africa LinkedIn alternative",
    "Africa best course platform",
    "Africa freelance marketplace",
    "Africa job opportunities",
    "Africa AI courses",
    "Africa programming courses",
    "Africa digital marketing",
    "Africa business network",
    "Africa professional network",
    "Africa course selling platform",
    "Africa learning management system",
    "Africa educational technology",
    "Africa e-learning platform",
    "Africa skill development",
    "Africa professional training",
    "Africa online learning",
    "Africa course marketplace",
    "Africa training platform",
    "Africa educational platform",
    "Sub-Saharan Africa learning platform",
    "Sub-Saharan Africa online courses",
    "Sub-Saharan Africa freelancing",
    "Sub-Saharan Africa jobs",
    "Sub-Saharan Africa tech courses",
    "Sub-Saharan Africa business courses",
    "Sub-Saharan Africa writers",
    "Sub-Saharan Africa bloggers",
    "Sub-Saharan Africa social platform",
    "West Africa learning platform",
    "West Africa online courses",
    "West Africa freelancing",
    "West Africa jobs",
    "West Africa tech courses",
    "West Africa business courses",
    "West Africa writers",
    "West Africa bloggers",
    "West Africa social platform",
    "East Africa learning platform",
    "East Africa online courses",
    "East Africa freelancing",
    "East Africa jobs",
    "East Africa tech courses",
    "East Africa business courses",
    "East Africa writers",
    "East Africa bloggers",
    "East Africa social platform",
    "Southern Africa learning platform",
    "Southern Africa online courses",
    "Southern Africa freelancing",
    "Southern Africa jobs",
    "Southern Africa tech courses",
    "Southern Africa business courses",
    "Southern Africa writers",
    "Southern Africa bloggers",
    "Southern Africa social platform",
    "Central Africa learning platform",
    "Central Africa online courses",
    "Central Africa freelancing",
    "Central Africa jobs",
    "Central Africa tech courses",
    "Central Africa business courses",
    "Central Africa writers",
    "Central Africa bloggers",
    "Central Africa social platform",
    "North Africa learning platform",
    "North Africa online courses",
    "North Africa freelancing",
    "North Africa jobs",
    "North Africa tech courses",
    "North Africa business courses",
    "North Africa writers",
    "North Africa bloggers",
    "North Africa social platform",
  ],

  // Global Tech Hubs
  globalTechHubs: [
    "Lagos tech courses",
    "Lagos learning platform",
    "Lagos freelancing",
    "Lagos jobs",
    "Lagos business courses",
    "Lagos writers",
    "Lagos bloggers",
    "Lagos social platform",
    "Lagos Udemy alternative",
    "Lagos Coursera alternative",
    "Lagos LinkedIn alternative",
    "Lagos best course platform",
    "Lagos freelance marketplace",
    "Lagos job opportunities",
    "Lagos AI courses",
    "Lagos programming courses",
    "Lagos digital marketing",
    "Lagos business network",
    "Lagos professional network",
    "Lagos course selling platform",
    "Lagos learning management system",
    "Lagos educational technology",
    "Lagos e-learning platform",
    "Lagos skill development",
    "Lagos professional training",
    "Lagos online learning",
    "Lagos course marketplace",
    "Lagos training platform",
    "Lagos educational platform",
    "Cairo tech courses",
    "Cairo learning platform",
    "Cairo freelancing",
    "Cairo jobs",
    "Cairo business courses",
    "Cairo writers",
    "Cairo bloggers",
    "Cairo social platform",
    "Cairo Udemy alternative",
    "Cairo Coursera alternative",
    "Cairo LinkedIn alternative",
    "Cairo best course platform",
    "Cairo freelance marketplace",
    "Cairo job opportunities",
    "Cairo AI courses",
    "Cairo programming courses",
    "Cairo digital marketing",
    "Cairo business network",
    "Cairo professional network",
    "Cairo course selling platform",
    "Cairo learning management system",
    "Cairo educational technology",
    "Cairo e-learning platform",
    "Cairo skill development",
    "Cairo professional training",
    "Cairo online learning",
    "Cairo course marketplace",
    "Cairo training platform",
    "Cairo educational platform",
    "Nairobi tech courses",
    "Nairobi learning platform",
    "Nairobi freelancing",
    "Nairobi jobs",
    "Nairobi business courses",
    "Nairobi writers",
    "Nairobi bloggers",
    "Nairobi social platform",
    "Nairobi Udemy alternative",
    "Nairobi Coursera alternative",
    "Nairobi LinkedIn alternative",
    "Nairobi best course platform",
    "Nairobi freelance marketplace",
    "Nairobi job opportunities",
    "Nairobi AI courses",
    "Nairobi programming courses",
    "Nairobi digital marketing",
    "Nairobi business network",
    "Nairobi professional network",
    "Nairobi course selling platform",
    "Nairobi learning management system",
    "Nairobi educational technology",
    "Nairobi e-learning platform",
    "Nairobi skill development",
    "Nairobi professional training",
    "Nairobi online learning",
    "Nairobi course marketplace",
    "Nairobi training platform",
    "Nairobi educational platform",
    "Cape Town tech courses",
    "Cape Town learning platform",
    "Cape Town freelancing",
    "Cape Town jobs",
    "Cape Town business courses",
    "Cape Town writers",
    "Cape Town bloggers",
    "Cape Town social platform",
    "Cape Town Udemy alternative",
    "Cape Town Coursera alternative",
    "Cape Town LinkedIn alternative",
    "Cape Town best course platform",
    "Cape Town freelance marketplace",
    "Cape Town job opportunities",
    "Cape Town AI courses",
    "Cape Town programming courses",
    "Cape Town digital marketing",
    "Cape Town business network",
    "Cape Town professional network",
    "Cape Town course selling platform",
    "Cape Town learning management system",
    "Cape Town educational technology",
    "Cape Town e-learning platform",
    "Cape Town skill development",
    "Cape Town professional training",
    "Cape Town online learning",
    "Cape Town course marketplace",
    "Cape Town training platform",
    "Cape Town educational platform",
    "Johannesburg tech courses",
    "Johannesburg learning platform",
    "Johannesburg freelancing",
    "Johannesburg jobs",
    "Johannesburg business courses",
    "Johannesburg writers",
    "Johannesburg bloggers",
    "Johannesburg social platform",
    "Johannesburg Udemy alternative",
    "Johannesburg Coursera alternative",
    "Johannesburg LinkedIn alternative",
    "Johannesburg best course platform",
    "Johannesburg freelance marketplace",
    "Johannesburg job opportunities",
    "Johannesburg AI courses",
    "Johannesburg programming courses",
    "Johannesburg digital marketing",
    "Johannesburg business network",
    "Johannesburg professional network",
    "Johannesburg course selling platform",
    "Johannesburg learning management system",
    "Johannesburg educational technology",
    "Johannesburg e-learning platform",
    "Johannesburg skill development",
    "Johannesburg professional training",
    "Johannesburg online learning",
    "Johannesburg course marketplace",
    "Johannesburg training platform",
    "Johannesburg educational platform",
    "Accra tech courses",
    "Accra learning platform",
    "Accra freelancing",
    "Accra jobs",
    "Accra business courses",
    "Accra writers",
    "Accra bloggers",
    "Accra social platform",
    "Accra Udemy alternative",
    "Accra Coursera alternative",
    "Accra LinkedIn alternative",
    "Accra best course platform",
    "Accra freelance marketplace",
    "Accra job opportunities",
    "Accra AI courses",
    "Accra programming courses",
    "Accra digital marketing",
    "Accra business network",
    "Accra professional network",
    "Accra course selling platform",
    "Accra learning management system",
    "Accra educational technology",
    "Accra e-learning platform",
    "Accra skill development",
    "Accra professional training",
    "Accra online learning",
    "Accra course marketplace",
    "Accra training platform",
    "Accra educational platform",
  ],

  // Emerging Markets
  emergingMarkets: [
    "Emerging markets learning platform",
    "Emerging markets online courses",
    "Emerging markets freelancing",
    "Emerging markets jobs",
    "Emerging markets tech courses",
    "Emerging markets business courses",
    "Emerging markets writers",
    "Emerging markets bloggers",
    "Emerging markets social platform",
    "Emerging markets Udemy alternative",
    "Emerging markets Coursera alternative",
    "Emerging markets LinkedIn alternative",
    "Emerging markets best course platform",
    "Emerging markets freelance marketplace",
    "Emerging markets job opportunities",
    "Emerging markets AI courses",
    "Emerging markets programming courses",
    "Emerging markets digital marketing",
    "Emerging markets business network",
    "Emerging markets professional network",
    "Emerging markets course selling platform",
    "Emerging markets learning management system",
    "Emerging markets educational technology",
    "Emerging markets e-learning platform",
    "Emerging markets skill development",
    "Emerging markets professional training",
    "Emerging markets online learning",
    "Emerging markets course marketplace",
    "Emerging markets training platform",
    "Emerging markets educational platform",
    "Developing countries learning platform",
    "Developing countries online courses",
    "Developing countries freelancing",
    "Developing countries jobs",
    "Developing countries tech courses",
    "Developing countries business courses",
    "Developing countries writers",
    "Developing countries bloggers",
    "Developing countries social platform",
    "Developing countries Udemy alternative",
    "Developing countries Coursera alternative",
    "Developing countries LinkedIn alternative",
    "Developing countries best course platform",
    "Developing countries freelance marketplace",
    "Developing countries job opportunities",
    "Developing countries AI courses",
    "Developing countries programming courses",
    "Developing countries digital marketing",
    "Developing countries business network",
    "Developing countries professional network",
    "Developing countries course selling platform",
    "Developing countries learning management system",
    "Developing countries educational technology",
    "Developing countries e-learning platform",
    "Developing countries skill development",
    "Developing countries professional training",
    "Developing countries online learning",
    "Developing countries course marketplace",
    "Developing countries training platform",
    "Developing countries educational platform",
  ],
};

// Combined global keywords
export const allGlobalKeywords = [
  ...Object.values(africanCountries).flat(),
  ...Object.values(internationalKeywords).flat(),
];

// High-priority global keywords
export const highPriorityGlobalKeywords = [
  "Africa learning platform",
  "African online courses",
  "Africa freelancing",
  "Africa jobs",
  "Africa tech courses",
  "Africa business courses",
  "Africa writers",
  "Africa bloggers",
  "Africa social platform",
  "Africa Udemy alternative",
  "Africa Coursera alternative",
  "Africa LinkedIn alternative",
  "Africa best course platform",
  "Africa freelance marketplace",
  "Africa job opportunities",
  "Africa AI courses",
  "Africa programming courses",
  "Africa digital marketing",
  "Africa business network",
  "Africa professional network",
  "Africa course selling platform",
  "Africa learning management system",
  "Africa educational technology",
  "Africa e-learning platform",
  "Africa skill development",
  "Africa professional training",
  "Africa online learning",
  "Africa course marketplace",
  "Africa training platform",
  "Africa educational platform",
  "Ghana learning platform",
  "Ghana online courses",
  "Ghana freelancing",
  "Ghana jobs",
  "Ghana tech courses",
  "Ghana business courses",
  "Ghana writers",
  "Ghana bloggers",
  "Ghana social platform",
  "Ghana Udemy alternative",
  "Ghana Coursera alternative",
  "Ghana LinkedIn alternative",
  "Ghana best course platform",
  "Ghana freelance marketplace",
  "Ghana job opportunities",
  "Ghana AI courses",
  "Ghana programming courses",
  "Ghana digital marketing",
  "Ghana business network",
  "Ghana professional network",
  "Ghana course selling platform",
  "Ghana learning management system",
  "Ghana educational technology",
  "Ghana e-learning platform",
  "Ghana skill development",
  "Ghana professional training",
  "Ghana online learning",
  "Ghana course marketplace",
  "Ghana training platform",
  "Ghana educational platform",
  "Kenya learning platform",
  "Kenya online courses",
  "Kenya freelancing",
  "Kenya jobs",
  "Kenya tech courses",
  "Kenya business courses",
  "Kenya writers",
  "Kenya bloggers",
  "Kenya social platform",
  "Kenya Udemy alternative",
  "Kenya Coursera alternative",
  "Kenya LinkedIn alternative",
  "Kenya best course platform",
  "Kenya freelance marketplace",
  "Kenya job opportunities",
  "Kenya AI courses",
  "Kenya programming courses",
  "Kenya digital marketing",
  "Kenya business network",
  "Kenya professional network",
  "Kenya course selling platform",
  "Kenya learning management system",
  "Kenya educational technology",
  "Kenya e-learning platform",
  "Kenya skill development",
  "Kenya professional training",
  "Kenya online learning",
  "Kenya course marketplace",
  "Kenya training platform",
  "Kenya educational platform",
  "South Africa learning platform",
  "South Africa online courses",
  "South Africa freelancing",
  "South Africa jobs",
  "South Africa tech courses",
  "South Africa business courses",
  "South Africa writers",
  "South Africa bloggers",
  "South Africa social platform",
  "South Africa Udemy alternative",
  "South Africa Coursera alternative",
  "South Africa LinkedIn alternative",
  "South Africa best course platform",
  "South Africa freelance marketplace",
  "South Africa job opportunities",
  "South Africa AI courses",
  "South Africa programming courses",
  "South Africa digital marketing",
  "South Africa business network",
  "South Africa professional network",
  "South Africa course selling platform",
  "South Africa learning management system",
  "South Africa educational technology",
  "South Africa e-learning platform",
  "South Africa skill development",
  "South Africa professional training",
  "South Africa online learning",
  "South Africa course marketplace",
  "South Africa training platform",
  "South Africa educational platform",
  "Egypt learning platform",
  "Egypt online courses",
  "Egypt freelancing",
  "Egypt jobs",
  "Egypt tech courses",
  "Egypt business courses",
  "Egypt writers",
  "Egypt bloggers",
  "Egypt social platform",
  "Egypt Udemy alternative",
  "Egypt Coursera alternative",
  "Egypt LinkedIn alternative",
  "Egypt best course platform",
  "Egypt freelance marketplace",
  "Egypt job opportunities",
  "Egypt AI courses",
  "Egypt programming courses",
  "Egypt digital marketing",
  "Egypt business network",
  "Egypt professional network",
  "Egypt course selling platform",
  "Egypt learning management system",
  "Egypt educational technology",
  "Egypt e-learning platform",
  "Egypt skill development",
  "Egypt professional training",
  "Egypt online learning",
  "Egypt course marketplace",
  "Egypt training platform",
  "Egypt educational platform",
  "Cameroon learning platform",
  "Cameroon online courses",
  "Cameroon freelancing",
  "Cameroon jobs",
  "Cameroon tech courses",
  "Cameroon business courses",
  "Cameroon writers",
  "Cameroon bloggers",
  "Cameroon social platform",
  "Cameroon Udemy alternative",
  "Cameroon Coursera alternative",
  "Cameroon LinkedIn alternative",
  "Cameroon best course platform",
  "Cameroon freelance marketplace",
  "Cameroon job opportunities",
  "Cameroon AI courses",
  "Cameroon programming courses",
  "Cameroon digital marketing",
  "Cameroon business network",
  "Cameroon professional network",
  "Cameroon course selling platform",
  "Cameroon learning management system",
  "Cameroon educational technology",
  "Cameroon e-learning platform",
  "Cameroon skill development",
  "Cameroon professional training",
  "Cameroon online learning",
  "Cameroon course marketplace",
  "Cameroon training platform",
  "Cameroon educational platform",
];

// Regional keyword mapping
export const regionalKeywords = {
  westAfrica: africanCountries.westAfrica,
  eastAfrica: africanCountries.eastAfrica,
  southernAfrica: africanCountries.southernAfrica,
  centralAfrica: africanCountries.centralAfrica,
  northAfrica: africanCountries.northAfrica,
  diaspora: internationalKeywords.diaspora,
  international: internationalKeywords.international,
  globalTechHubs: internationalKeywords.globalTechHubs,
  emergingMarkets: internationalKeywords.emergingMarkets,
};

// Country-specific keyword mapping
export const countryKeywords = {
  nigeria: [
    "Nigeria learning platform",
    "Nigerian online courses",
    "Nigeria freelancing",
    "Nigeria jobs",
    "Nigeria tech courses",
    "Nigeria business courses",
    "Nigeria writers",
    "Nigeria bloggers",
    "Nigeria social platform",
    "Nigeria Udemy alternative",
    "Nigeria Coursera alternative",
    "Nigeria LinkedIn alternative",
    "Nigeria best course platform",
    "Nigeria freelance marketplace",
    "Nigeria job opportunities",
    "Nigeria AI courses",
    "Nigeria programming courses",
    "Nigeria digital marketing",
    "Nigeria business network",
    "Nigeria professional network",
    "Nigeria course selling platform",
    "Nigeria learning management system",
    "Nigeria educational technology",
    "Nigeria e-learning platform",
    "Nigeria skill development",
    "Nigeria professional training",
    "Nigeria online learning",
    "Nigeria course marketplace",
    "Nigeria training platform",
    "Nigeria educational platform",
  ],
  ghana: africanCountries.westAfrica.slice(0, 30),
  kenya: africanCountries.eastAfrica.slice(0, 30),
  southAfrica: africanCountries.southernAfrica.slice(0, 30),
  egypt: africanCountries.northAfrica.slice(0, 30),
  cameroon: africanCountries.centralAfrica.slice(0, 30),
};

// Language-specific keywords (for future multilingual support)


// Language-specific keywords (for future multilingual support)
export const languageKeywords = {
  english: allGlobalKeywords,
  french: [
    "plateforme d'apprentissage Afrique",
    "cours en ligne Afrique",
    "freelance Afrique",
    "emplois Afrique",
    "cours tech Afrique",
    "cours business Afrique",
    "écrivains Afrique",
    "bloggers Afrique",
    "plateforme sociale Afrique",
    "alternative Udemy Afrique",
    "alternative Coursera Afrique",
    "alternative LinkedIn Afrique",
    "meilleure plateforme cours Afrique",
    "marché freelance Afrique",
    "opportunités emploi Afrique",
    "cours IA Afrique",
    "cours programmation Afrique",
    "marketing digital Afrique",
    "réseau business Afrique",
    "réseau professionnel Afrique",
    "plateforme vente cours Afrique",
    "système gestion apprentissage Afrique",
    "technologie éducative Afrique",
    "plateforme e-learning Afrique",
    "développement compétences Afrique",
    "formation professionnelle Afrique",
    "apprentissage en ligne Afrique",
    "marché cours Afrique",
    "plateforme formation Afrique",
    "plateforme éducative Afrique",
  ],
  arabic: [
    "منصة التعلم أفريقيا",
    "دورات عبر الإنترنت أفريقيا",
    "العمل الحر أفريقيا",
    "الوظائف أفريقيا",
    "دورات التكنولوجيا أفريقيا",
    "دورات الأعمال أفريقيا",
    "الكتاب أفريقيا",
    "المدونون أفريقيا",
    "المنصة الاجتماعية أفريقيا",
    "بديل Udemy أفريقيا",
    "بديل Coursera أفريقيا",
    "بديل LinkedIn أفريقيا",
    "أفضل منصة دورات أفريقيا",
    "سوق العمل الحر أفريقيا",
    "فرص العمل أفريقيا",
    "دورات الذكاء الاصطناعي أفريقيا",
    "دورات البرمجة أفريقيا",
    "التسويق الرقمي أفريقيا",
    "شبكة الأعمال أفريقيا",
    "الشبكة المهنية أفريقيا",
    "منصة بيع الدورات أفريقيا",
    "نظام إدارة التعلم أفريقيا",
    "التكنولوجيا التعليمية أفريقيا",
    "منصة التعلم الإلكتروني أفريقيا",
    "تطوير المهارات أفريقيا",
    "التدريب المهني أفريقيا",
    "التعلم عبر الإنترنت أفريقيا",
    "سوق الدورات أفريقيا",
    "منصة التدريب أفريقيا",
    "المنصة التعليمية أفريقيا",
  ],
  portuguese: [
    "plataforma de aprendizado África",
    "cursos online África",
    "freelance África",
    "empregos África",
    "cursos tech África",
    "cursos business África",
    "escritores África",
    "bloggers África",
    "plataforma social África",
    "alternativa Udemy África",
    "alternativa Coursera África",
    "alternativa LinkedIn África",
    "melhor plataforma cursos África",
    "mercado freelance África",
    "oportunidades emprego África",
    "cursos IA África",
    "cursos programação África",
    "marketing digital África",
    "rede business África",
    "rede profissional África",
    "plataforma venda cursos África",
    "sistema gestão aprendizado África",
    "tecnologia educativa África",
    "plataforma e-learning África",
    "desenvolvimento competências África",
    "formação profissional África",
    "aprendizado online África",
    "mercado cursos África",
    "plataforma formação África",
    "plataforma educativa África",
  ],
};
