// Comprehensive Nigerian Keywords Database for SEO Domination

export const nigerianKeywords = {
  // Core Platform Keywords
  platform: [
    "Nigeria learning platform",
    "Nigerian online courses",
    "Nigeria Udemy alternative",
    "Nigeria best course platform",
    "Nigerian education platform",
    "Nigeria skill development",
    "Nigerian professional training",
    "Nigeria online learning",
    "Nigerian course marketplace",
    "Nigeria educational technology",
    "Nigerian e-learning platform",
    "Nigeria digital education",
    "Nigerian training platform",
    "Nigeria course selling platform",
    "Nigerian learning management system",
  ],

  // AI & Technology Keywords
  ai: [
    "AI courses Nigeria",
    "Artificial Intelligence Nigeria",
    "Machine Learning Nigeria",
    "Nigeria AI training",
    "Nigerian AI courses",
    "AI bootcamp Nigeria",
    "Nigeria AI certification",
    "Nigerian AI skills",
    "AI jobs Nigeria",
    "Nigeria AI development",
    "Nigerian AI professionals",
    "AI freelancing Nigeria",
    "Nigeria AI marketplace",
    "Nigerian AI community",
    "AI tools Nigeria",
  ],

  // Business & Entrepreneurship
  business: [
    "Nigeria business courses",
    "Nigerian entrepreneurship",
    "Nigeria startup courses",
    "Nigerian business training",
    "Nigeria business skills",
    "Nigerian business network",
    "Nigeria business platform",
    "Nigerian business community",
    "Nigeria business development",
    "Nigerian business coaching",
    "Nigeria business mentorship",
    "Nigerian business opportunities",
    "Nigeria business marketplace",
    "Nigerian business networking",
    "Nigeria business education",
  ],

  // Freelancing & Jobs
  freelancing: [
    "Nigeria freelancing",
    "Nigerian freelancers",
    "Nigeria freelance marketplace",
    "Nigerian freelance jobs",
    "Nigeria freelance platform",
    "Nigerian freelance community",
    "Nigeria freelance opportunities",
    "Nigerian freelance services",
    "Nigeria freelance network",
    "Nigerian freelance skills",
    "Nigeria freelance training",
    "Nigerian freelance business",
    "Nigeria freelance marketplace",
    "Nigerian freelance gigs",
    "Nigeria freelance work",
  ],

  jobs: [
    "Nigeria jobs",
    "Nigerian job opportunities",
    "Nigeria job platform",
    "Nigerian job search",
    "Nigeria job marketplace",
    "Nigerian job network",
    "Nigeria job community",
    "Nigerian job board",
    "Nigeria job portal",
    "Nigerian job services",
    "Nigeria job training",
    "Nigerian job skills",
    "Nigeria job placement",
    "Nigerian job recruitment",
    "Nigeria job opportunities",
  ],

  // Social & Networking
  social: [
    "Nigeria social platform",
    "Nigerian social network",
    "Nigeria business network",
    "Nigerian professional network",
    "Nigeria social business",
    "Nigerian social community",
    "Nigeria networking platform",
    "Nigerian networking community",
    "Nigeria social marketplace",
    "Nigerian social business network",
    "Nigeria professional community",
    "Nigerian business social network",
    "Nigeria social learning",
    "Nigerian social platform",
    "Nigeria community platform",
  ],

  // Writing & Content Creation
  writing: [
    "Nigeria writers",
    "Nigerian content writers",
    "Nigeria writing jobs",
    "Nigerian writing platform",
    "Nigeria content creation",
    "Nigerian writing community",
    "Nigeria freelance writing",
    "Nigerian writing services",
    "Nigeria writing marketplace",
    "Nigerian writing opportunities",
    "Nigeria writing network",
    "Nigerian writing skills",
    "Nigeria writing training",
    "Nigerian writing business",
    "Nigeria writing platform",
  ],

  bloggers: [
    "Nigeria bloggers",
    "Nigerian blogging",
    "Nigeria blog platform",
    "Nigerian blog community",
    "Nigeria blogging courses",
    "Nigerian blog training",
    "Nigeria blog marketplace",
    "Nigerian blog network",
    "Nigeria blog opportunities",
    "Nigerian blog services",
    "Nigeria blog monetization",
    "Nigerian blog skills",
    "Nigeria blog business",
    "Nigerian blog platform",
    "Nigeria blog community",
  ],

  // Tech & Programming
  tech: [
    "Nigeria tech",
    "Nigerian tech courses",
    "Nigeria programming",
    "Nigerian coding bootcamp",
    "Nigeria software development",
    "Nigerian tech training",
    "Nigeria tech skills",
    "Nigerian tech jobs",
    "Nigeria tech community",
    "Nigerian tech platform",
    "Nigeria tech marketplace",
    "Nigerian tech network",
    "Nigeria tech opportunities",
    "Nigerian tech education",
    "Nigeria tech business",
  ],

  // Cities & Locations
  cities: [
    "Lagos courses",
    "Abuja training",
    "Port Harcourt learning",
    "Kano education",
    "Ibadan courses",
    "Lagos tech courses",
    "Abuja business training",
    "Port Harcourt programming",
    "Kano online learning",
    "Ibadan skill development",
    "Lagos freelancing",
    "Abuja job opportunities",
    "Port Harcourt business",
    "Kano tech jobs",
    "Ibadan writing jobs",
  ],

  // Competitor Keywords
  competitors: [
    "Nigeria Udemy",
    "Nigerian Udemy alternative",
    "Nigeria Coursera alternative",
    "Nigerian Skillshare alternative",
    "Nigeria LinkedIn Learning alternative",
    "Nigerian MasterClass alternative",
    "Nigeria better than Udemy",
    "Nigerian course platform better than Udemy",
    "Nigeria local course platform",
    "Nigerian course marketplace",
    "Nigeria educational platform",
    "Nigerian learning platform",
    "Nigeria course selling",
    "Nigerian course creation",
    "Nigeria course monetization",
  ],

  // Industry-Specific
  industries: [
    "Nigeria fintech courses",
    "Nigerian healthcare training",
    "Nigeria agriculture courses",
    "Nigerian real estate training",
    "Nigeria marketing courses",
    "Nigerian sales training",
    "Nigeria customer service",
    "Nigerian project management",
    "Nigeria digital marketing",
    "Nigerian social media marketing",
    "Nigeria SEO training",
    "Nigerian content marketing",
    "Nigeria email marketing",
    "Nigerian affiliate marketing",
    "Nigeria influencer marketing",
  ],

  // Skill-Specific
  skills: [
    "Nigeria Python courses",
    "Nigerian JavaScript training",
    "Nigeria React courses",
    "Nigerian Node.js training",
    "Nigeria data science",
    "Nigerian analytics courses",
    "Nigeria cloud computing",
    "Nigerian AWS training",
    "Nigeria cybersecurity",
    "Nigerian ethical hacking",
    "Nigeria blockchain courses",
    "Nigerian cryptocurrency training",
    "Nigeria web development",
    "Nigerian mobile app development",
    "Nigeria UI/UX design",
  ],

  // Long-tail Keywords
  longTail: [
    "best online courses in Nigeria",
    "top Nigerian learning platforms",
    "where to learn programming in Nigeria",
    "Nigerian tech skills training",
    "best freelancing platform Nigeria",
    "Nigerian job search platform",
    "how to start freelancing in Nigeria",
    "Nigerian business networking platform",
    "best writing jobs Nigeria",
    "Nigerian content creation platform",
    "top tech courses Lagos",
    "best business training Abuja",
    "Nigerian online education platform",
    "learn coding Nigeria",
    "Nigerian professional development",
  ],

  // Content creation keywords
  content: [
    "content creation Nigeria",
    "Nigerian content writing",
    "Nigeria copywriting courses",
    "Nigerian content marketing",
    "Nigeria blog writing",
    "Nigerian social media content",
    "Nigeria content strategy",
    "Nigerian digital content",
    "Nigeria content production",
    "Nigerian content planning",
  ],

  // Networking keywords
  networking: [
    "Nigerian professional networking",
    "Nigeria business networking",
    "Nigerian networking events",
    "Nigeria professional connections",
    "Nigerian business relationships",
    "Nigeria networking platform",
    "Nigerian career networking",
    "Nigeria industry networking",
    "Nigerian professional community",
    "Nigeria business connections",
  ],
};

// Combined keyword array for easy use
export const allNigerianKeywords = Object.values(nigerianKeywords).flat();

// High-priority keywords for immediate targeting
export const highPriorityKeywords = [
  "Nigeria learning platform",
  "Nigerian online courses",
  "Nigeria Udemy alternative",
  "Nigeria best course platform",
  "Nigerian freelancers",
  "Nigeria freelance marketplace",
  "Nigeria jobs",
  "Nigerian job opportunities",
  "Nigeria tech courses",
  "Nigerian AI courses",
  "Nigeria business courses",
  "Nigerian writers",
  "Nigeria bloggers",
  "Nigeria social platform",
  "Nigerian business network",
];

// Search intent mapping
export const searchIntentKeywords = {
  informational: [
    "what is",
    "how to",
    "best way to",
    "learn",
    "training",
    "courses",
    "education",
  ],
  navigational: [
    "Nigeria learning platform",
    "Nigerian course platform",
    "Dealo platform",
    "Nigeria freelancing platform",
  ],
  transactional: [
    "buy courses",
    "enroll",
    "sign up",
    "join",
    "register",
    "purchase",
    "subscribe",
  ],
  commercial: [
    "best",
    "top",
    "compare",
    "review",
    "alternative",
    "vs",
    "better than",
  ],
};

// Seasonal keywords
export const seasonalKeywords = {
  newYear: [
    "New Year learning goals Nigeria",
    "Nigerian New Year skill development",
    "Nigeria 2024 courses",
    "Nigerian resolution courses",
  ],
  graduation: [
    "Nigerian graduate courses",
    "Nigeria post-graduation training",
    "Nigerian graduate job preparation",
    "Nigeria graduate skill development",
  ],
  jobHunting: [
    "Nigeria job search courses",
    "Nigerian interview preparation",
    "Nigeria resume writing courses",
    "Nigerian job application training",
  ],
};

// Competitor analysis keywords
export const competitorKeywords = {
  udemy: [
    "Nigeria Udemy alternative",
    "better than Udemy Nigeria",
    "Nigerian Udemy competitor",
    "Nigeria local Udemy",
    "Nigerian course platform vs Udemy",
  ],
  coursera: [
    "Nigeria Coursera alternative",
    "Nigerian Coursera competitor",
    "Nigeria local Coursera",
    "Nigerian course platform vs Coursera",
  ],
  linkedin: [
    "Nigeria LinkedIn Learning alternative",
    "Nigerian LinkedIn competitor",
    "Nigeria local LinkedIn Learning",
    "Nigerian professional platform vs LinkedIn",
  ],
};
